class DiamondsController < ApplicationController
  def new
    @diamond = Diamond.new
  end
  
  def index
    # @diamonds = Diamond.all
    #kaminariでページネーション
    @diamonds = Diamond.page(params[:page])
    
 
    #indexページからグラフ描画の引数を取得
    weight =
    color =
    clar =
    start_date =
    end_date =
    min_price =
    max_price =
    
    
    weight_group_03_color_D_IF = Diamond.where(weight: 0.3).where(color: "D").where(clar: "IF")
    weight_group_03_color_E_IF = Diamond.where(weight: 0.3).where(color: "E").where(clar: "IF")
    weight_group_03_color_F_IF = Diamond.where(weight: 0.3).where(color: "F").where(clar: "IF")
    weight_group_03_color_G_IF = Diamond.where(weight: 0.3).where(color: "G").where(clar: "IF")
    weight_group_03_color_H_IF = Diamond.where(weight: 0.3).where(color: "H").where(clar: "IF")
    weight_group_03_color_I_IF = Diamond.where(weight: 0.3).where(color: "I").where(clar: "IF")
    weight_group_03_color_J_IF = Diamond.where(weight: 0.3).where(color: "J").where(clar: "IF")
    weight_group_03_color_K_IF = Diamond.where(weight: 0.3).where(color: "K").where(clar: "IF")
    weight_group_03_color_L_IF = Diamond.where(weight: 0.3).where(color: "L").where(clar: "IF")
    weight_group_03_color_M_IF = Diamond.where(weight: 0.3).where(color: "M").where(clar: "IF")
    
    weight_group_03_color_D_VVS1 = Diamond.where(weight: 0.3).where(color: "D").where(clar: "VVS1")
    weight_group_03_color_E_VVS1 = Diamond.where(weight: 0.3).where(color: "E").where(clar: "VVS1")
    weight_group_03_color_F_VVS1 = Diamond.where(weight: 0.3).where(color: "F").where(clar: "VVS1")
    weight_group_03_color_G_VVS1 = Diamond.where(weight: 0.3).where(color: "G").where(clar: "VVS1")
    weight_group_03_color_H_VVS1 = Diamond.where(weight: 0.3).where(color: "H").where(clar: "VVS1")
    weight_group_03_color_I_VVS1 = Diamond.where(weight: 0.3).where(color: "I").where(clar: "VVS1")
    weight_group_03_color_J_VVS1 = Diamond.where(weight: 0.3).where(color: "J").where(clar: "VVS1")
    weight_group_03_color_K_VVS1 = Diamond.where(weight: 0.3).where(color: "K").where(clar: "VVS1")
    weight_group_03_color_L_VVS1 = Diamond.where(weight: 0.3).where(color: "L").where(clar: "VVS1")
    weight_group_03_color_M_VVS1 = Diamond.where(weight: 0.3).where(color: "M").where(clar: "VVS1")
    
    weight_group_03_color_D_VVS2 = Diamond.where(weight: 0.3).where(color: "D").where(clar: "VVS2")
    weight_group_03_color_E_VVS2 = Diamond.where(weight: 0.3).where(color: "E").where(clar: "VVS2")
    weight_group_03_color_F_VVS2 = Diamond.where(weight: 0.3).where(color: "F").where(clar: "VVS2")
    weight_group_03_color_G_VVS2 = Diamond.where(weight: 0.3).where(color: "G").where(clar: "VVS2")
    weight_group_03_color_H_VVS2 = Diamond.where(weight: 0.3).where(color: "H").where(clar: "VVS2")
    weight_group_03_color_I_VVS2 = Diamond.where(weight: 0.3).where(color: "I").where(clar: "VVS2")
    weight_group_03_color_J_VVS2 = Diamond.where(weight: 0.3).where(color: "J").where(clar: "VVS2")
    weight_group_03_color_K_VVS2 = Diamond.where(weight: 0.3).where(color: "K").where(clar: "VVS2")
    weight_group_03_color_L_VVS2 = Diamond.where(weight: 0.3).where(color: "L").where(clar: "VVS2")
    weight_group_03_color_M_VVS2 = Diamond.where(weight: 0.3).where(color: "M").where(clar: "VVS2")
    
    weight_group_03_color_D_VS1 = Diamond.where(weight: 0.3).where(color: "D").where(clar: "VS1")
    weight_group_03_color_E_VS1 = Diamond.where(weight: 0.3).where(color: "E").where(clar: "VS1")
    weight_group_03_color_F_VS1 = Diamond.where(weight: 0.3).where(color: "F").where(clar: "VS1")
    weight_group_03_color_G_VS1 = Diamond.where(weight: 0.3).where(color: "G").where(clar: "VS1")
    weight_group_03_color_H_VS1 = Diamond.where(weight: 0.3).where(color: "H").where(clar: "VS1")
    weight_group_03_color_I_VS1 = Diamond.where(weight: 0.3).where(color: "I").where(clar: "VS1")
    weight_group_03_color_J_VS1 = Diamond.where(weight: 0.3).where(color: "J").where(clar: "VS1")
    weight_group_03_color_K_VS1 = Diamond.where(weight: 0.3).where(color: "K").where(clar: "VS1")
    weight_group_03_color_L_VS1 = Diamond.where(weight: 0.3).where(color: "L").where(clar: "VS1")
    weight_group_03_color_M_VS1 = Diamond.where(weight: 0.3).where(color: "M").where(clar: "VS1")
    
    weight_group_03_color_D_VS2 = Diamond.where(weight: 0.3).where(color: "D").where(clar: "VS2")
    weight_group_03_color_E_VS2 = Diamond.where(weight: 0.3).where(color: "E").where(clar: "VS2")
    weight_group_03_color_F_VS2 = Diamond.where(weight: 0.3).where(color: "F").where(clar: "VS2")
    weight_group_03_color_G_VS2 = Diamond.where(weight: 0.3).where(color: "G").where(clar: "VS2")
    weight_group_03_color_H_VS2 = Diamond.where(weight: 0.3).where(color: "H").where(clar: "VS2")
    weight_group_03_color_I_VS2 = Diamond.where(weight: 0.3).where(color: "I").where(clar: "VS2")
    weight_group_03_color_J_VS2 = Diamond.where(weight: 0.3).where(color: "J").where(clar: "VS2")
    weight_group_03_color_K_VS2 = Diamond.where(weight: 0.3).where(color: "K").where(clar: "VS2")
    weight_group_03_color_L_VS2 = Diamond.where(weight: 0.3).where(color: "L").where(clar: "VS2")
    weight_group_03_color_M_VS2 = Diamond.where(weight: 0.3).where(color: "M").where(clar: "VS2")
    
    weight_group_03_color_D_SI1 = Diamond.where(weight: 0.3).where(color: "D").where(clar: "SI1")
    weight_group_03_color_E_SI1 = Diamond.where(weight: 0.3).where(color: "E").where(clar: "SI1")
    weight_group_03_color_F_SI1 = Diamond.where(weight: 0.3).where(color: "F").where(clar: "SI1")
    weight_group_03_color_G_SI1 = Diamond.where(weight: 0.3).where(color: "G").where(clar: "SI1")
    weight_group_03_color_H_SI1 = Diamond.where(weight: 0.3).where(color: "H").where(clar: "SI1")
    weight_group_03_color_I_SI1 = Diamond.where(weight: 0.3).where(color: "I").where(clar: "SI1")
    weight_group_03_color_J_SI1 = Diamond.where(weight: 0.3).where(color: "J").where(clar: "SI1")
    weight_group_03_color_K_SI1 = Diamond.where(weight: 0.3).where(color: "K").where(clar: "SI1")
    weight_group_03_color_L_SI1 = Diamond.where(weight: 0.3).where(color: "L").where(clar: "SI1")
    weight_group_03_color_M_SI1 = Diamond.where(weight: 0.3).where(color: "M").where(clar: "SI1")
    
    weight_group_03_color_D_SI2 = Diamond.where(weight: 0.3).where(color: "D").where(clar: "SI2")
    weight_group_03_color_E_SI2 = Diamond.where(weight: 0.3).where(color: "E").where(clar: "SI2")
    weight_group_03_color_F_SI2 = Diamond.where(weight: 0.3).where(color: "F").where(clar: "SI2")
    weight_group_03_color_G_SI2 = Diamond.where(weight: 0.3).where(color: "G").where(clar: "SI2")
    weight_group_03_color_H_SI2 = Diamond.where(weight: 0.3).where(color: "H").where(clar: "SI2")
    weight_group_03_color_I_SI2 = Diamond.where(weight: 0.3).where(color: "I").where(clar: "SI2")
    weight_group_03_color_J_SI2 = Diamond.where(weight: 0.3).where(color: "J").where(clar: "SI2")
    weight_group_03_color_K_SI2 = Diamond.where(weight: 0.3).where(color: "K").where(clar: "SI2")
    weight_group_03_color_L_SI2 = Diamond.where(weight: 0.3).where(color: "L").where(clar: "SI2")
    weight_group_03_color_M_SI2 = Diamond.where(weight: 0.3).where(color: "M").where(clar: "SI2")
    
    #weight0.4-----------------------
    weight_group_04_color_D_IF = Diamond.where(weight: 0.4).where(color: "D").where(clar: "IF")
    weight_group_04_color_E_IF = Diamond.where(weight: 0.4).where(color: "E").where(clar: "IF")
    weight_group_04_color_F_IF = Diamond.where(weight: 0.4).where(color: "F").where(clar: "IF")
    weight_group_04_color_G_IF = Diamond.where(weight: 0.4).where(color: "G").where(clar: "IF")
    weight_group_04_color_H_IF = Diamond.where(weight: 0.4).where(color: "H").where(clar: "IF")
    weight_group_04_color_I_IF = Diamond.where(weight: 0.4).where(color: "I").where(clar: "IF")
    weight_group_04_color_J_IF = Diamond.where(weight: 0.4).where(color: "J").where(clar: "IF")
    weight_group_04_color_K_IF = Diamond.where(weight: 0.4).where(color: "K").where(clar: "IF")
    weight_group_04_color_L_IF = Diamond.where(weight: 0.4).where(color: "L").where(clar: "IF")
    weight_group_04_color_M_IF = Diamond.where(weight: 0.4).where(color: "M").where(clar: "IF")
    
    weight_group_04_color_D_VVS1 = Diamond.where(weight: 0.4).where(color: "D").where(clar: "VVS1")
    weight_group_04_color_E_VVS1 = Diamond.where(weight: 0.4).where(color: "E").where(clar: "VVS1")
    weight_group_04_color_F_VVS1 = Diamond.where(weight: 0.4).where(color: "F").where(clar: "VVS1")
    weight_group_04_color_G_VVS1 = Diamond.where(weight: 0.4).where(color: "G").where(clar: "VVS1")
    weight_group_04_color_H_VVS1 = Diamond.where(weight: 0.4).where(color: "H").where(clar: "VVS1")
    weight_group_04_color_I_VVS1 = Diamond.where(weight: 0.4).where(color: "I").where(clar: "VVS1")
    weight_group_04_color_J_VVS1 = Diamond.where(weight: 0.4).where(color: "J").where(clar: "VVS1")
    weight_group_04_color_K_VVS1 = Diamond.where(weight: 0.4).where(color: "K").where(clar: "VVS1")
    weight_group_04_color_L_VVS1 = Diamond.where(weight: 0.4).where(color: "L").where(clar: "VVS1")
    weight_group_04_color_M_VVS1 = Diamond.where(weight: 0.4).where(color: "M").where(clar: "VVS1")
    
    weight_group_04_color_D_VVS2 = Diamond.where(weight: 0.4).where(color: "D").where(clar: "VVS2")
    weight_group_04_color_E_VVS2 = Diamond.where(weight: 0.4).where(color: "E").where(clar: "VVS2")
    weight_group_04_color_F_VVS2 = Diamond.where(weight: 0.4).where(color: "F").where(clar: "VVS2")
    weight_group_04_color_G_VVS2 = Diamond.where(weight: 0.4).where(color: "G").where(clar: "VVS2")
    weight_group_04_color_H_VVS2 = Diamond.where(weight: 0.4).where(color: "H").where(clar: "VVS2")
    weight_group_04_color_I_VVS2 = Diamond.where(weight: 0.4).where(color: "I").where(clar: "VVS2")
    weight_group_04_color_J_VVS2 = Diamond.where(weight: 0.4).where(color: "J").where(clar: "VVS2")
    weight_group_04_color_K_VVS2 = Diamond.where(weight: 0.4).where(color: "K").where(clar: "VVS2")
    weight_group_04_color_L_VVS2 = Diamond.where(weight: 0.4).where(color: "L").where(clar: "VVS2")
    weight_group_04_color_M_VVS2 = Diamond.where(weight: 0.4).where(color: "M").where(clar: "VVS2")
    
    weight_group_04_color_D_VS1 = Diamond.where(weight: 0.4).where(color: "D").where(clar: "VS1")
    weight_group_04_color_E_VS1 = Diamond.where(weight: 0.4).where(color: "E").where(clar: "VS1")
    weight_group_04_color_F_VS1 = Diamond.where(weight: 0.4).where(color: "F").where(clar: "VS1")
    weight_group_04_color_G_VS1 = Diamond.where(weight: 0.4).where(color: "G").where(clar: "VS1")
    weight_group_04_color_H_VS1 = Diamond.where(weight: 0.4).where(color: "H").where(clar: "VS1")
    weight_group_04_color_I_VS1 = Diamond.where(weight: 0.4).where(color: "I").where(clar: "VS1")
    weight_group_04_color_J_VS1 = Diamond.where(weight: 0.4).where(color: "J").where(clar: "VS1")
    weight_group_04_color_K_VS1 = Diamond.where(weight: 0.4).where(color: "K").where(clar: "VS1")
    weight_group_04_color_L_VS1 = Diamond.where(weight: 0.4).where(color: "L").where(clar: "VS1")
    weight_group_04_color_M_VS1 = Diamond.where(weight: 0.4).where(color: "M").where(clar: "VS1")
    
    weight_group_04_color_D_VS2 = Diamond.where(weight: 0.4).where(color: "D").where(clar: "VS2")
    weight_group_04_color_E_VS2 = Diamond.where(weight: 0.4).where(color: "E").where(clar: "VS2")
    weight_group_04_color_F_VS2 = Diamond.where(weight: 0.4).where(color: "F").where(clar: "VS2")
    weight_group_04_color_G_VS2 = Diamond.where(weight: 0.4).where(color: "G").where(clar: "VS2")
    weight_group_04_color_H_VS2 = Diamond.where(weight: 0.4).where(color: "H").where(clar: "VS2")
    weight_group_04_color_I_VS2 = Diamond.where(weight: 0.4).where(color: "I").where(clar: "VS2")
    weight_group_04_color_J_VS2 = Diamond.where(weight: 0.4).where(color: "J").where(clar: "VS2")
    weight_group_04_color_K_VS2 = Diamond.where(weight: 0.4).where(color: "K").where(clar: "VS2")
    weight_group_04_color_L_VS2 = Diamond.where(weight: 0.4).where(color: "L").where(clar: "VS2")
    weight_group_04_color_M_VS2 = Diamond.where(weight: 0.4).where(color: "M").where(clar: "VS2")
    
    weight_group_04_color_D_SI1 = Diamond.where(weight: 0.4).where(color: "D").where(clar: "SI1")
    weight_group_04_color_E_SI1 = Diamond.where(weight: 0.4).where(color: "E").where(clar: "SI1")
    weight_group_04_color_F_SI1 = Diamond.where(weight: 0.4).where(color: "F").where(clar: "SI1")
    weight_group_04_color_G_SI1 = Diamond.where(weight: 0.4).where(color: "G").where(clar: "SI1")
    weight_group_04_color_H_SI1 = Diamond.where(weight: 0.4).where(color: "H").where(clar: "SI1")
    weight_group_04_color_I_SI1 = Diamond.where(weight: 0.4).where(color: "I").where(clar: "SI1")
    weight_group_04_color_J_SI1 = Diamond.where(weight: 0.4).where(color: "J").where(clar: "SI1")
    weight_group_04_color_K_SI1 = Diamond.where(weight: 0.4).where(color: "K").where(clar: "SI1")
    weight_group_04_color_L_SI1 = Diamond.where(weight: 0.4).where(color: "L").where(clar: "SI1")
    weight_group_04_color_M_SI1 = Diamond.where(weight: 0.4).where(color: "M").where(clar: "SI1")
    
    weight_group_04_color_D_SI2 = Diamond.where(weight: 0.4).where(color: "D").where(clar: "SI2")
    weight_group_04_color_E_SI2 = Diamond.where(weight: 0.4).where(color: "E").where(clar: "SI2")
    weight_group_04_color_F_SI2 = Diamond.where(weight: 0.4).where(color: "F").where(clar: "SI2")
    weight_group_04_color_G_SI2 = Diamond.where(weight: 0.4).where(color: "G").where(clar: "SI2")
    weight_group_04_color_H_SI2 = Diamond.where(weight: 0.4).where(color: "H").where(clar: "SI2")
    weight_group_04_color_I_SI2 = Diamond.where(weight: 0.4).where(color: "I").where(clar: "SI2")
    weight_group_04_color_J_SI2 = Diamond.where(weight: 0.4).where(color: "J").where(clar: "SI2")
    weight_group_04_color_K_SI2 = Diamond.where(weight: 0.4).where(color: "K").where(clar: "SI2")
    weight_group_04_color_L_SI2 = Diamond.where(weight: 0.4).where(color: "L").where(clar: "SI2")
    weight_group_04_color_M_SI2 = Diamond.where(weight: 0.4).where(color: "M").where(clar: "SI2")
    
    #weight0.5-----------------------
    weight_group_05_color_D_IF = Diamond.where(weight: 0.5).where(color: "D").where(clar: "IF")
    weight_group_05_color_E_IF = Diamond.where(weight: 0.5).where(color: "E").where(clar: "IF")
    weight_group_05_color_F_IF = Diamond.where(weight: 0.5).where(color: "F").where(clar: "IF")
    weight_group_05_color_G_IF = Diamond.where(weight: 0.5).where(color: "G").where(clar: "IF")
    weight_group_05_color_H_IF = Diamond.where(weight: 0.5).where(color: "H").where(clar: "IF")
    weight_group_05_color_I_IF = Diamond.where(weight: 0.5).where(color: "I").where(clar: "IF")
    weight_group_05_color_J_IF = Diamond.where(weight: 0.5).where(color: "J").where(clar: "IF")
    weight_group_05_color_K_IF = Diamond.where(weight: 0.5).where(color: "K").where(clar: "IF")
    weight_group_05_color_L_IF = Diamond.where(weight: 0.5).where(color: "L").where(clar: "IF")
    weight_group_05_color_M_IF = Diamond.where(weight: 0.5).where(color: "M").where(clar: "IF")
    
    weight_group_05_color_D_VVS1 = Diamond.where(weight: 0.5).where(color: "D").where(clar: "VVS1")
    weight_group_05_color_E_VVS1 = Diamond.where(weight: 0.5).where(color: "E").where(clar: "VVS1")
    weight_group_05_color_F_VVS1 = Diamond.where(weight: 0.5).where(color: "F").where(clar: "VVS1")
    weight_group_05_color_G_VVS1 = Diamond.where(weight: 0.5).where(color: "G").where(clar: "VVS1")
    weight_group_05_color_H_VVS1 = Diamond.where(weight: 0.5).where(color: "H").where(clar: "VVS1")
    weight_group_05_color_I_VVS1 = Diamond.where(weight: 0.5).where(color: "I").where(clar: "VVS1")
    weight_group_05_color_J_VVS1 = Diamond.where(weight: 0.5).where(color: "J").where(clar: "VVS1")
    weight_group_05_color_K_VVS1 = Diamond.where(weight: 0.5).where(color: "K").where(clar: "VVS1")
    weight_group_05_color_L_VVS1 = Diamond.where(weight: 0.5).where(color: "L").where(clar: "VVS1")
    weight_group_05_color_M_VVS1 = Diamond.where(weight: 0.5).where(color: "M").where(clar: "VVS1")
    
    weight_group_05_color_D_VVS2 = Diamond.where(weight: 0.5).where(color: "D").where(clar: "VVS2")
    weight_group_05_color_E_VVS2 = Diamond.where(weight: 0.5).where(color: "E").where(clar: "VVS2")
    weight_group_05_color_F_VVS2 = Diamond.where(weight: 0.5).where(color: "F").where(clar: "VVS2")
    weight_group_05_color_G_VVS2 = Diamond.where(weight: 0.5).where(color: "G").where(clar: "VVS2")
    weight_group_05_color_H_VVS2 = Diamond.where(weight: 0.5).where(color: "H").where(clar: "VVS2")
    weight_group_05_color_I_VVS2 = Diamond.where(weight: 0.5).where(color: "I").where(clar: "VVS2")
    weight_group_05_color_J_VVS2 = Diamond.where(weight: 0.5).where(color: "J").where(clar: "VVS2")
    weight_group_05_color_K_VVS2 = Diamond.where(weight: 0.5).where(color: "K").where(clar: "VVS2")
    weight_group_05_color_L_VVS2 = Diamond.where(weight: 0.5).where(color: "L").where(clar: "VVS2")
    weight_group_05_color_M_VVS2 = Diamond.where(weight: 0.5).where(color: "M").where(clar: "VVS2")
    
    weight_group_05_color_D_VS1 = Diamond.where(weight: 0.5).where(color: "D").where(clar: "VS1")
    weight_group_05_color_E_VS1 = Diamond.where(weight: 0.5).where(color: "E").where(clar: "VS1")
    weight_group_05_color_F_VS1 = Diamond.where(weight: 0.5).where(color: "F").where(clar: "VS1")
    weight_group_05_color_G_VS1 = Diamond.where(weight: 0.5).where(color: "G").where(clar: "VS1")
    weight_group_05_color_H_VS1 = Diamond.where(weight: 0.5).where(color: "H").where(clar: "VS1")
    weight_group_05_color_I_VS1 = Diamond.where(weight: 0.5).where(color: "I").where(clar: "VS1")
    weight_group_05_color_J_VS1 = Diamond.where(weight: 0.5).where(color: "J").where(clar: "VS1")
    weight_group_05_color_K_VS1 = Diamond.where(weight: 0.5).where(color: "K").where(clar: "VS1")
    weight_group_05_color_L_VS1 = Diamond.where(weight: 0.5).where(color: "L").where(clar: "VS1")
    weight_group_05_color_M_VS1 = Diamond.where(weight: 0.5).where(color: "M").where(clar: "VS1")
    
    weight_group_05_color_D_VS2 = Diamond.where(weight: 0.5).where(color: "D").where(clar: "VS2")
    weight_group_05_color_E_VS2 = Diamond.where(weight: 0.5).where(color: "E").where(clar: "VS2")
    weight_group_05_color_F_VS2 = Diamond.where(weight: 0.5).where(color: "F").where(clar: "VS2")
    weight_group_05_color_G_VS2 = Diamond.where(weight: 0.5).where(color: "G").where(clar: "VS2")
    weight_group_05_color_H_VS2 = Diamond.where(weight: 0.5).where(color: "H").where(clar: "VS2")
    weight_group_05_color_I_VS2 = Diamond.where(weight: 0.5).where(color: "I").where(clar: "VS2")
    weight_group_05_color_J_VS2 = Diamond.where(weight: 0.5).where(color: "J").where(clar: "VS2")
    weight_group_05_color_K_VS2 = Diamond.where(weight: 0.5).where(color: "K").where(clar: "VS2")
    weight_group_05_color_L_VS2 = Diamond.where(weight: 0.5).where(color: "L").where(clar: "VS2")
    weight_group_05_color_M_VS2 = Diamond.where(weight: 0.5).where(color: "M").where(clar: "VS2")
    
    weight_group_05_color_D_SI1 = Diamond.where(weight: 0.5).where(color: "D").where(clar: "SI1")
    weight_group_05_color_E_SI1 = Diamond.where(weight: 0.5).where(color: "E").where(clar: "SI1")
    weight_group_05_color_F_SI1 = Diamond.where(weight: 0.5).where(color: "F").where(clar: "SI1")
    weight_group_05_color_G_SI1 = Diamond.where(weight: 0.5).where(color: "G").where(clar: "SI1")
    weight_group_05_color_H_SI1 = Diamond.where(weight: 0.5).where(color: "H").where(clar: "SI1")
    weight_group_05_color_I_SI1 = Diamond.where(weight: 0.5).where(color: "I").where(clar: "SI1")
    weight_group_05_color_J_SI1 = Diamond.where(weight: 0.5).where(color: "J").where(clar: "SI1")
    weight_group_05_color_K_SI1 = Diamond.where(weight: 0.5).where(color: "K").where(clar: "SI1")
    weight_group_05_color_L_SI1 = Diamond.where(weight: 0.5).where(color: "L").where(clar: "SI1")
    weight_group_05_color_M_SI1 = Diamond.where(weight: 0.5).where(color: "M").where(clar: "SI1")
    
    weight_group_05_color_D_SI2 = Diamond.where(weight: 0.5).where(color: "D").where(clar: "SI2")
    weight_group_05_color_E_SI2 = Diamond.where(weight: 0.5).where(color: "E").where(clar: "SI2")
    weight_group_05_color_F_SI2 = Diamond.where(weight: 0.5).where(color: "F").where(clar: "SI2")
    weight_group_05_color_G_SI2 = Diamond.where(weight: 0.5).where(color: "G").where(clar: "SI2")
    weight_group_05_color_H_SI2 = Diamond.where(weight: 0.5).where(color: "H").where(clar: "SI2")
    weight_group_05_color_I_SI2 = Diamond.where(weight: 0.5).where(color: "I").where(clar: "SI2")
    weight_group_05_color_J_SI2 = Diamond.where(weight: 0.5).where(color: "J").where(clar: "SI2")
    weight_group_05_color_K_SI2 = Diamond.where(weight: 0.5).where(color: "K").where(clar: "SI2")
    weight_group_05_color_L_SI2 = Diamond.where(weight: 0.5).where(color: "L").where(clar: "SI2")
    weight_group_05_color_M_SI2 = Diamond.where(weight: 0.5).where(color: "M").where(clar: "SI2")
    
    #weight0.6-----------------------
    weight_group_06_color_D_IF = Diamond.where(weight: 0.6).where(color: "D").where(clar: "IF")
    weight_group_06_color_E_IF = Diamond.where(weight: 0.6).where(color: "E").where(clar: "IF")
    weight_group_06_color_F_IF = Diamond.where(weight: 0.6).where(color: "F").where(clar: "IF")
    weight_group_06_color_G_IF = Diamond.where(weight: 0.6).where(color: "G").where(clar: "IF")
    weight_group_06_color_H_IF = Diamond.where(weight: 0.6).where(color: "H").where(clar: "IF")
    weight_group_06_color_I_IF = Diamond.where(weight: 0.6).where(color: "I").where(clar: "IF")
    weight_group_06_color_J_IF = Diamond.where(weight: 0.6).where(color: "J").where(clar: "IF")
    weight_group_06_color_K_IF = Diamond.where(weight: 0.6).where(color: "K").where(clar: "IF")
    weight_group_06_color_L_IF = Diamond.where(weight: 0.6).where(color: "L").where(clar: "IF")
    weight_group_06_color_M_IF = Diamond.where(weight: 0.6).where(color: "M").where(clar: "IF")
    
    weight_group_06_color_D_VVS1 = Diamond.where(weight: 0.6).where(color: "D").where(clar: "VVS1")
    weight_group_06_color_E_VVS1 = Diamond.where(weight: 0.6).where(color: "E").where(clar: "VVS1")
    weight_group_06_color_F_VVS1 = Diamond.where(weight: 0.6).where(color: "F").where(clar: "VVS1")
    weight_group_06_color_G_VVS1 = Diamond.where(weight: 0.6).where(color: "G").where(clar: "VVS1")
    weight_group_06_color_H_VVS1 = Diamond.where(weight: 0.6).where(color: "H").where(clar: "VVS1")
    weight_group_06_color_I_VVS1 = Diamond.where(weight: 0.6).where(color: "I").where(clar: "VVS1")
    weight_group_06_color_J_VVS1 = Diamond.where(weight: 0.6).where(color: "J").where(clar: "VVS1")
    weight_group_06_color_K_VVS1 = Diamond.where(weight: 0.6).where(color: "K").where(clar: "VVS1")
    weight_group_06_color_L_VVS1 = Diamond.where(weight: 0.6).where(color: "L").where(clar: "VVS1")
    weight_group_06_color_M_VVS1 = Diamond.where(weight: 0.6).where(color: "M").where(clar: "VVS1")
    
    weight_group_06_color_D_VVS2 = Diamond.where(weight: 0.6).where(color: "D").where(clar: "VVS2")
    weight_group_06_color_E_VVS2 = Diamond.where(weight: 0.6).where(color: "E").where(clar: "VVS2")
    weight_group_06_color_F_VVS2 = Diamond.where(weight: 0.6).where(color: "F").where(clar: "VVS2")
    weight_group_06_color_G_VVS2 = Diamond.where(weight: 0.6).where(color: "G").where(clar: "VVS2")
    weight_group_06_color_H_VVS2 = Diamond.where(weight: 0.6).where(color: "H").where(clar: "VVS2")
    weight_group_06_color_I_VVS2 = Diamond.where(weight: 0.6).where(color: "I").where(clar: "VVS2")
    weight_group_06_color_J_VVS2 = Diamond.where(weight: 0.6).where(color: "J").where(clar: "VVS2")
    weight_group_06_color_K_VVS2 = Diamond.where(weight: 0.6).where(color: "K").where(clar: "VVS2")
    weight_group_06_color_L_VVS2 = Diamond.where(weight: 0.6).where(color: "L").where(clar: "VVS2")
    weight_group_06_color_M_VVS2 = Diamond.where(weight: 0.6).where(color: "M").where(clar: "VVS2")
    
    weight_group_06_color_D_VS1 = Diamond.where(weight: 0.6).where(color: "D").where(clar: "VS1")
    weight_group_06_color_E_VS1 = Diamond.where(weight: 0.6).where(color: "E").where(clar: "VS1")
    weight_group_06_color_F_VS1 = Diamond.where(weight: 0.6).where(color: "F").where(clar: "VS1")
    weight_group_06_color_G_VS1 = Diamond.where(weight: 0.6).where(color: "G").where(clar: "VS1")
    weight_group_06_color_H_VS1 = Diamond.where(weight: 0.6).where(color: "H").where(clar: "VS1")
    weight_group_06_color_I_VS1 = Diamond.where(weight: 0.6).where(color: "I").where(clar: "VS1")
    weight_group_06_color_J_VS1 = Diamond.where(weight: 0.6).where(color: "J").where(clar: "VS1")
    weight_group_06_color_K_VS1 = Diamond.where(weight: 0.6).where(color: "K").where(clar: "VS1")
    weight_group_06_color_L_VS1 = Diamond.where(weight: 0.6).where(color: "L").where(clar: "VS1")
    weight_group_06_color_M_VS1 = Diamond.where(weight: 0.6).where(color: "M").where(clar: "VS1")
    
    weight_group_06_color_D_VS2 = Diamond.where(weight: 0.6).where(color: "D").where(clar: "VS2")
    weight_group_06_color_E_VS2 = Diamond.where(weight: 0.6).where(color: "E").where(clar: "VS2")
    weight_group_06_color_F_VS2 = Diamond.where(weight: 0.6).where(color: "F").where(clar: "VS2")
    weight_group_06_color_G_VS2 = Diamond.where(weight: 0.6).where(color: "G").where(clar: "VS2")
    weight_group_06_color_H_VS2 = Diamond.where(weight: 0.6).where(color: "H").where(clar: "VS2")
    weight_group_06_color_I_VS2 = Diamond.where(weight: 0.6).where(color: "I").where(clar: "VS2")
    weight_group_06_color_J_VS2 = Diamond.where(weight: 0.6).where(color: "J").where(clar: "VS2")
    weight_group_06_color_K_VS2 = Diamond.where(weight: 0.6).where(color: "K").where(clar: "VS2")
    weight_group_06_color_L_VS2 = Diamond.where(weight: 0.6).where(color: "L").where(clar: "VS2")
    weight_group_06_color_M_VS2 = Diamond.where(weight: 0.6).where(color: "M").where(clar: "VS2")
    
    weight_group_06_color_D_SI1 = Diamond.where(weight: 0.6).where(color: "D").where(clar: "SI1")
    weight_group_06_color_E_SI1 = Diamond.where(weight: 0.6).where(color: "E").where(clar: "SI1")
    weight_group_06_color_F_SI1 = Diamond.where(weight: 0.6).where(color: "F").where(clar: "SI1")
    weight_group_06_color_G_SI1 = Diamond.where(weight: 0.6).where(color: "G").where(clar: "SI1")
    weight_group_06_color_H_SI1 = Diamond.where(weight: 0.6).where(color: "H").where(clar: "SI1")
    weight_group_06_color_I_SI1 = Diamond.where(weight: 0.6).where(color: "I").where(clar: "SI1")
    weight_group_06_color_J_SI1 = Diamond.where(weight: 0.6).where(color: "J").where(clar: "SI1")
    weight_group_06_color_K_SI1 = Diamond.where(weight: 0.6).where(color: "K").where(clar: "SI1")
    weight_group_06_color_L_SI1 = Diamond.where(weight: 0.6).where(color: "L").where(clar: "SI1")
    weight_group_06_color_M_SI1 = Diamond.where(weight: 0.6).where(color: "M").where(clar: "SI1")
    
    weight_group_06_color_D_SI2 = Diamond.where(weight: 0.6).where(color: "D").where(clar: "SI2")
    weight_group_06_color_E_SI2 = Diamond.where(weight: 0.6).where(color: "E").where(clar: "SI2")
    weight_group_06_color_F_SI2 = Diamond.where(weight: 0.6).where(color: "F").where(clar: "SI2")
    weight_group_06_color_G_SI2 = Diamond.where(weight: 0.6).where(color: "G").where(clar: "SI2")
    weight_group_06_color_H_SI2 = Diamond.where(weight: 0.6).where(color: "H").where(clar: "SI2")
    weight_group_06_color_I_SI2 = Diamond.where(weight: 0.6).where(color: "I").where(clar: "SI2")
    weight_group_06_color_J_SI2 = Diamond.where(weight: 0.6).where(color: "J").where(clar: "SI2")
    weight_group_06_color_K_SI2 = Diamond.where(weight: 0.6).where(color: "K").where(clar: "SI2")
    weight_group_06_color_L_SI2 = Diamond.where(weight: 0.6).where(color: "L").where(clar: "SI2")
    weight_group_06_color_M_SI2 = Diamond.where(weight: 0.6).where(color: "M").where(clar: "SI2")
    
    #weight0.7-----------------------
    weight_group_07_color_D_IF = Diamond.where(weight: 0.7).where(color: "D").where(clar: "IF")
    weight_group_07_color_E_IF = Diamond.where(weight: 0.7).where(color: "E").where(clar: "IF")
    weight_group_07_color_F_IF = Diamond.where(weight: 0.7).where(color: "F").where(clar: "IF")
    weight_group_07_color_G_IF = Diamond.where(weight: 0.7).where(color: "G").where(clar: "IF")
    weight_group_07_color_H_IF = Diamond.where(weight: 0.7).where(color: "H").where(clar: "IF")
    weight_group_07_color_I_IF = Diamond.where(weight: 0.7).where(color: "I").where(clar: "IF")
    weight_group_07_color_J_IF = Diamond.where(weight: 0.7).where(color: "J").where(clar: "IF")
    weight_group_07_color_K_IF = Diamond.where(weight: 0.7).where(color: "K").where(clar: "IF")
    weight_group_07_color_L_IF = Diamond.where(weight: 0.7).where(color: "L").where(clar: "IF")
    weight_group_07_color_M_IF = Diamond.where(weight: 0.7).where(color: "M").where(clar: "IF")
    
    weight_group_07_color_D_VVS1 = Diamond.where(weight: 0.7).where(color: "D").where(clar: "VVS1")
    weight_group_07_color_E_VVS1 = Diamond.where(weight: 0.7).where(color: "E").where(clar: "VVS1")
    weight_group_07_color_F_VVS1 = Diamond.where(weight: 0.7).where(color: "F").where(clar: "VVS1")
    weight_group_07_color_G_VVS1 = Diamond.where(weight: 0.7).where(color: "G").where(clar: "VVS1")
    weight_group_07_color_H_VVS1 = Diamond.where(weight: 0.7).where(color: "H").where(clar: "VVS1")
    weight_group_07_color_I_VVS1 = Diamond.where(weight: 0.7).where(color: "I").where(clar: "VVS1")
    weight_group_07_color_J_VVS1 = Diamond.where(weight: 0.7).where(color: "J").where(clar: "VVS1")
    weight_group_07_color_K_VVS1 = Diamond.where(weight: 0.7).where(color: "K").where(clar: "VVS1")
    weight_group_07_color_L_VVS1 = Diamond.where(weight: 0.7).where(color: "L").where(clar: "VVS1")
    weight_group_07_color_M_VVS1 = Diamond.where(weight: 0.7).where(color: "M").where(clar: "VVS1")
    
    weight_group_07_color_D_VVS2 = Diamond.where(weight: 0.7).where(color: "D").where(clar: "VVS2")
    weight_group_07_color_E_VVS2 = Diamond.where(weight: 0.7).where(color: "E").where(clar: "VVS2")
    weight_group_07_color_F_VVS2 = Diamond.where(weight: 0.7).where(color: "F").where(clar: "VVS2")
    weight_group_07_color_G_VVS2 = Diamond.where(weight: 0.7).where(color: "G").where(clar: "VVS2")
    weight_group_07_color_H_VVS2 = Diamond.where(weight: 0.7).where(color: "H").where(clar: "VVS2")
    weight_group_07_color_I_VVS2 = Diamond.where(weight: 0.7).where(color: "I").where(clar: "VVS2")
    weight_group_07_color_J_VVS2 = Diamond.where(weight: 0.7).where(color: "J").where(clar: "VVS2")
    weight_group_07_color_K_VVS2 = Diamond.where(weight: 0.7).where(color: "K").where(clar: "VVS2")
    weight_group_07_color_L_VVS2 = Diamond.where(weight: 0.7).where(color: "L").where(clar: "VVS2")
    weight_group_07_color_M_VVS2 = Diamond.where(weight: 0.7).where(color: "M").where(clar: "VVS2")
    
    weight_group_07_color_D_VS1 = Diamond.where(weight: 0.7).where(color: "D").where(clar: "VS1")
    weight_group_07_color_E_VS1 = Diamond.where(weight: 0.7).where(color: "E").where(clar: "VS1")
    weight_group_07_color_F_VS1 = Diamond.where(weight: 0.7).where(color: "F").where(clar: "VS1")
    weight_group_07_color_G_VS1 = Diamond.where(weight: 0.7).where(color: "G").where(clar: "VS1")
    weight_group_07_color_H_VS1 = Diamond.where(weight: 0.7).where(color: "H").where(clar: "VS1")
    weight_group_07_color_I_VS1 = Diamond.where(weight: 0.7).where(color: "I").where(clar: "VS1")
    weight_group_07_color_J_VS1 = Diamond.where(weight: 0.7).where(color: "J").where(clar: "VS1")
    weight_group_07_color_K_VS1 = Diamond.where(weight: 0.7).where(color: "K").where(clar: "VS1")
    weight_group_07_color_L_VS1 = Diamond.where(weight: 0.7).where(color: "L").where(clar: "VS1")
    weight_group_07_color_M_VS1 = Diamond.where(weight: 0.7).where(color: "M").where(clar: "VS1")
    
    weight_group_07_color_D_VS2 = Diamond.where(weight: 0.7).where(color: "D").where(clar: "VS2")
    weight_group_07_color_E_VS2 = Diamond.where(weight: 0.7).where(color: "E").where(clar: "VS2")
    weight_group_07_color_F_VS2 = Diamond.where(weight: 0.7).where(color: "F").where(clar: "VS2")
    weight_group_07_color_G_VS2 = Diamond.where(weight: 0.7).where(color: "G").where(clar: "VS2")
    weight_group_07_color_H_VS2 = Diamond.where(weight: 0.7).where(color: "H").where(clar: "VS2")
    weight_group_07_color_I_VS2 = Diamond.where(weight: 0.7).where(color: "I").where(clar: "VS2")
    weight_group_07_color_J_VS2 = Diamond.where(weight: 0.7).where(color: "J").where(clar: "VS2")
    weight_group_07_color_K_VS2 = Diamond.where(weight: 0.7).where(color: "K").where(clar: "VS2")
    weight_group_07_color_L_VS2 = Diamond.where(weight: 0.7).where(color: "L").where(clar: "VS2")
    weight_group_07_color_M_VS2 = Diamond.where(weight: 0.7).where(color: "M").where(clar: "VS2")
    
    weight_group_07_color_D_SI1 = Diamond.where(weight: 0.7).where(color: "D").where(clar: "SI1")
    weight_group_07_color_E_SI1 = Diamond.where(weight: 0.7).where(color: "E").where(clar: "SI1")
    weight_group_07_color_F_SI1 = Diamond.where(weight: 0.7).where(color: "F").where(clar: "SI1")
    weight_group_07_color_G_SI1 = Diamond.where(weight: 0.7).where(color: "G").where(clar: "SI1")
    weight_group_07_color_H_SI1 = Diamond.where(weight: 0.7).where(color: "H").where(clar: "SI1")
    weight_group_07_color_I_SI1 = Diamond.where(weight: 0.7).where(color: "I").where(clar: "SI1")
    weight_group_07_color_J_SI1 = Diamond.where(weight: 0.7).where(color: "J").where(clar: "SI1")
    weight_group_07_color_K_SI1 = Diamond.where(weight: 0.7).where(color: "K").where(clar: "SI1")
    weight_group_07_color_L_SI1 = Diamond.where(weight: 0.7).where(color: "L").where(clar: "SI1")
    weight_group_07_color_M_SI1 = Diamond.where(weight: 0.7).where(color: "M").where(clar: "SI1")
    
    weight_group_07_color_D_SI2 = Diamond.where(weight: 0.7).where(color: "D").where(clar: "SI2")
    weight_group_07_color_E_SI2 = Diamond.where(weight: 0.7).where(color: "E").where(clar: "SI2")
    weight_group_07_color_F_SI2 = Diamond.where(weight: 0.7).where(color: "F").where(clar: "SI2")
    weight_group_07_color_G_SI2 = Diamond.where(weight: 0.7).where(color: "G").where(clar: "SI2")
    weight_group_07_color_H_SI2 = Diamond.where(weight: 0.7).where(color: "H").where(clar: "SI2")
    weight_group_07_color_I_SI2 = Diamond.where(weight: 0.7).where(color: "I").where(clar: "SI2")
    weight_group_07_color_J_SI2 = Diamond.where(weight: 0.7).where(color: "J").where(clar: "SI2")
    weight_group_07_color_K_SI2 = Diamond.where(weight: 0.7).where(color: "K").where(clar: "SI2")
    weight_group_07_color_L_SI2 = Diamond.where(weight: 0.7).where(color: "L").where(clar: "SI2")
    weight_group_07_color_M_SI2 = Diamond.where(weight: 0.7).where(color: "M").where(clar: "SI2")
    
    #weight0.8-----------------------
    weight_group_08_color_D_IF = Diamond.where(weight: 0.8).where(color: "D").where(clar: "IF")
    weight_group_08_color_E_IF = Diamond.where(weight: 0.8).where(color: "E").where(clar: "IF")
    weight_group_08_color_F_IF = Diamond.where(weight: 0.8).where(color: "F").where(clar: "IF")
    weight_group_08_color_G_IF = Diamond.where(weight: 0.8).where(color: "G").where(clar: "IF")
    weight_group_08_color_H_IF = Diamond.where(weight: 0.8).where(color: "H").where(clar: "IF")
    weight_group_08_color_I_IF = Diamond.where(weight: 0.8).where(color: "I").where(clar: "IF")
    weight_group_08_color_J_IF = Diamond.where(weight: 0.8).where(color: "J").where(clar: "IF")
    weight_group_08_color_K_IF = Diamond.where(weight: 0.8).where(color: "K").where(clar: "IF")
    weight_group_08_color_L_IF = Diamond.where(weight: 0.8).where(color: "L").where(clar: "IF")
    weight_group_08_color_M_IF = Diamond.where(weight: 0.8).where(color: "M").where(clar: "IF")
    
    weight_group_08_color_D_VVS1 = Diamond.where(weight: 0.8).where(color: "D").where(clar: "VVS1")
    weight_group_08_color_E_VVS1 = Diamond.where(weight: 0.8).where(color: "E").where(clar: "VVS1")
    weight_group_08_color_F_VVS1 = Diamond.where(weight: 0.8).where(color: "F").where(clar: "VVS1")
    weight_group_08_color_G_VVS1 = Diamond.where(weight: 0.8).where(color: "G").where(clar: "VVS1")
    weight_group_08_color_H_VVS1 = Diamond.where(weight: 0.8).where(color: "H").where(clar: "VVS1")
    weight_group_08_color_I_VVS1 = Diamond.where(weight: 0.8).where(color: "I").where(clar: "VVS1")
    weight_group_08_color_J_VVS1 = Diamond.where(weight: 0.8).where(color: "J").where(clar: "VVS1")
    weight_group_08_color_K_VVS1 = Diamond.where(weight: 0.8).where(color: "K").where(clar: "VVS1")
    weight_group_08_color_L_VVS1 = Diamond.where(weight: 0.8).where(color: "L").where(clar: "VVS1")
    weight_group_08_color_M_VVS1 = Diamond.where(weight: 0.8).where(color: "M").where(clar: "VVS1")
    
    weight_group_08_color_D_VVS2 = Diamond.where(weight: 0.8).where(color: "D").where(clar: "VVS2")
    weight_group_08_color_E_VVS2 = Diamond.where(weight: 0.8).where(color: "E").where(clar: "VVS2")
    weight_group_08_color_F_VVS2 = Diamond.where(weight: 0.8).where(color: "F").where(clar: "VVS2")
    weight_group_08_color_G_VVS2 = Diamond.where(weight: 0.8).where(color: "G").where(clar: "VVS2")
    weight_group_08_color_H_VVS2 = Diamond.where(weight: 0.8).where(color: "H").where(clar: "VVS2")
    weight_group_08_color_I_VVS2 = Diamond.where(weight: 0.8).where(color: "I").where(clar: "VVS2")
    weight_group_08_color_J_VVS2 = Diamond.where(weight: 0.8).where(color: "J").where(clar: "VVS2")
    weight_group_08_color_K_VVS2 = Diamond.where(weight: 0.8).where(color: "K").where(clar: "VVS2")
    weight_group_08_color_L_VVS2 = Diamond.where(weight: 0.8).where(color: "L").where(clar: "VVS2")
    weight_group_08_color_M_VVS2 = Diamond.where(weight: 0.8).where(color: "M").where(clar: "VVS2")
    
    weight_group_08_color_D_VS1 = Diamond.where(weight: 0.8).where(color: "D").where(clar: "VS1")
    weight_group_08_color_E_VS1 = Diamond.where(weight: 0.8).where(color: "E").where(clar: "VS1")
    weight_group_08_color_F_VS1 = Diamond.where(weight: 0.8).where(color: "F").where(clar: "VS1")
    weight_group_08_color_G_VS1 = Diamond.where(weight: 0.8).where(color: "G").where(clar: "VS1")
    weight_group_08_color_H_VS1 = Diamond.where(weight: 0.8).where(color: "H").where(clar: "VS1")
    weight_group_08_color_I_VS1 = Diamond.where(weight: 0.8).where(color: "I").where(clar: "VS1")
    weight_group_08_color_J_VS1 = Diamond.where(weight: 0.8).where(color: "J").where(clar: "VS1")
    weight_group_08_color_K_VS1 = Diamond.where(weight: 0.8).where(color: "K").where(clar: "VS1")
    weight_group_08_color_L_VS1 = Diamond.where(weight: 0.8).where(color: "L").where(clar: "VS1")
    weight_group_08_color_M_VS1 = Diamond.where(weight: 0.8).where(color: "M").where(clar: "VS1")
    
    weight_group_08_color_D_VS2 = Diamond.where(weight: 0.8).where(color: "D").where(clar: "VS2")
    weight_group_08_color_E_VS2 = Diamond.where(weight: 0.8).where(color: "E").where(clar: "VS2")
    weight_group_08_color_F_VS2 = Diamond.where(weight: 0.8).where(color: "F").where(clar: "VS2")
    weight_group_08_color_G_VS2 = Diamond.where(weight: 0.8).where(color: "G").where(clar: "VS2")
    weight_group_08_color_H_VS2 = Diamond.where(weight: 0.8).where(color: "H").where(clar: "VS2")
    weight_group_08_color_I_VS2 = Diamond.where(weight: 0.8).where(color: "I").where(clar: "VS2")
    weight_group_08_color_J_VS2 = Diamond.where(weight: 0.8).where(color: "J").where(clar: "VS2")
    weight_group_08_color_K_VS2 = Diamond.where(weight: 0.8).where(color: "K").where(clar: "VS2")
    weight_group_08_color_L_VS2 = Diamond.where(weight: 0.8).where(color: "L").where(clar: "VS2")
    weight_group_08_color_M_VS2 = Diamond.where(weight: 0.8).where(color: "M").where(clar: "VS2")
    
    weight_group_08_color_D_SI1 = Diamond.where(weight: 0.8).where(color: "D").where(clar: "SI1")
    weight_group_08_color_E_SI1 = Diamond.where(weight: 0.8).where(color: "E").where(clar: "SI1")
    weight_group_08_color_F_SI1 = Diamond.where(weight: 0.8).where(color: "F").where(clar: "SI1")
    weight_group_08_color_G_SI1 = Diamond.where(weight: 0.8).where(color: "G").where(clar: "SI1")
    weight_group_08_color_H_SI1 = Diamond.where(weight: 0.8).where(color: "H").where(clar: "SI1")
    weight_group_08_color_I_SI1 = Diamond.where(weight: 0.8).where(color: "I").where(clar: "SI1")
    weight_group_08_color_J_SI1 = Diamond.where(weight: 0.8).where(color: "J").where(clar: "SI1")
    weight_group_08_color_K_SI1 = Diamond.where(weight: 0.8).where(color: "K").where(clar: "SI1")
    weight_group_08_color_L_SI1 = Diamond.where(weight: 0.8).where(color: "L").where(clar: "SI1")
    weight_group_08_color_M_SI1 = Diamond.where(weight: 0.8).where(color: "M").where(clar: "SI1")
    
    weight_group_08_color_D_SI2 = Diamond.where(weight: 0.8).where(color: "D").where(clar: "SI2")
    weight_group_08_color_E_SI2 = Diamond.where(weight: 0.8).where(color: "E").where(clar: "SI2")
    weight_group_08_color_F_SI2 = Diamond.where(weight: 0.8).where(color: "F").where(clar: "SI2")
    weight_group_08_color_G_SI2 = Diamond.where(weight: 0.8).where(color: "G").where(clar: "SI2")
    weight_group_08_color_H_SI2 = Diamond.where(weight: 0.8).where(color: "H").where(clar: "SI2")
    weight_group_08_color_I_SI2 = Diamond.where(weight: 0.8).where(color: "I").where(clar: "SI2")
    weight_group_08_color_J_SI2 = Diamond.where(weight: 0.8).where(color: "J").where(clar: "SI2")
    weight_group_08_color_K_SI2 = Diamond.where(weight: 0.8).where(color: "K").where(clar: "SI2")
    weight_group_08_color_L_SI2 = Diamond.where(weight: 0.8).where(color: "L").where(clar: "SI2")
    weight_group_08_color_M_SI2 = Diamond.where(weight: 0.8).where(color: "M").where(clar: "SI2")
   
   
    #weight0.9-----------------------
    weight_group_09_color_D_IF = Diamond.where(weight: 0.9).where(color: "D").where(clar: "IF")
    weight_group_09_color_E_IF = Diamond.where(weight: 0.9).where(color: "E").where(clar: "IF")
    weight_group_09_color_F_IF = Diamond.where(weight: 0.9).where(color: "F").where(clar: "IF")
    weight_group_09_color_G_IF = Diamond.where(weight: 0.9).where(color: "G").where(clar: "IF")
    weight_group_09_color_H_IF = Diamond.where(weight: 0.9).where(color: "H").where(clar: "IF")
    weight_group_09_color_I_IF = Diamond.where(weight: 0.9).where(color: "I").where(clar: "IF")
    weight_group_09_color_J_IF = Diamond.where(weight: 0.9).where(color: "J").where(clar: "IF")
    weight_group_09_color_K_IF = Diamond.where(weight: 0.9).where(color: "K").where(clar: "IF")
    weight_group_09_color_L_IF = Diamond.where(weight: 0.9).where(color: "L").where(clar: "IF")
    weight_group_09_color_M_IF = Diamond.where(weight: 0.9).where(color: "M").where(clar: "IF")
    
    weight_group_09_color_D_VVS1 = Diamond.where(weight: 0.9).where(color: "D").where(clar: "VVS1")
    weight_group_09_color_E_VVS1 = Diamond.where(weight: 0.9).where(color: "E").where(clar: "VVS1")
    weight_group_09_color_F_VVS1 = Diamond.where(weight: 0.9).where(color: "F").where(clar: "VVS1")
    weight_group_09_color_G_VVS1 = Diamond.where(weight: 0.9).where(color: "G").where(clar: "VVS1")
    weight_group_09_color_H_VVS1 = Diamond.where(weight: 0.9).where(color: "H").where(clar: "VVS1")
    weight_group_09_color_I_VVS1 = Diamond.where(weight: 0.9).where(color: "I").where(clar: "VVS1")
    weight_group_09_color_J_VVS1 = Diamond.where(weight: 0.9).where(color: "J").where(clar: "VVS1")
    weight_group_09_color_K_VVS1 = Diamond.where(weight: 0.9).where(color: "K").where(clar: "VVS1")
    weight_group_09_color_L_VVS1 = Diamond.where(weight: 0.9).where(color: "L").where(clar: "VVS1")
    weight_group_09_color_M_VVS1 = Diamond.where(weight: 0.9).where(color: "M").where(clar: "VVS1")
    
    weight_group_09_color_D_VVS2 = Diamond.where(weight: 0.9).where(color: "D").where(clar: "VVS2")
    weight_group_09_color_E_VVS2 = Diamond.where(weight: 0.9).where(color: "E").where(clar: "VVS2")
    weight_group_09_color_F_VVS2 = Diamond.where(weight: 0.9).where(color: "F").where(clar: "VVS2")
    weight_group_09_color_G_VVS2 = Diamond.where(weight: 0.9).where(color: "G").where(clar: "VVS2")
    weight_group_09_color_H_VVS2 = Diamond.where(weight: 0.9).where(color: "H").where(clar: "VVS2")
    weight_group_09_color_I_VVS2 = Diamond.where(weight: 0.9).where(color: "I").where(clar: "VVS2")
    weight_group_09_color_J_VVS2 = Diamond.where(weight: 0.9).where(color: "J").where(clar: "VVS2")
    weight_group_09_color_K_VVS2 = Diamond.where(weight: 0.9).where(color: "K").where(clar: "VVS2")
    weight_group_09_color_L_VVS2 = Diamond.where(weight: 0.9).where(color: "L").where(clar: "VVS2")
    weight_group_09_color_M_VVS2 = Diamond.where(weight: 0.9).where(color: "M").where(clar: "VVS2")
    
    weight_group_09_color_D_VS1 = Diamond.where(weight: 0.9).where(color: "D").where(clar: "VS1")
    weight_group_09_color_E_VS1 = Diamond.where(weight: 0.9).where(color: "E").where(clar: "VS1")
    weight_group_09_color_F_VS1 = Diamond.where(weight: 0.9).where(color: "F").where(clar: "VS1")
    weight_group_09_color_G_VS1 = Diamond.where(weight: 0.9).where(color: "G").where(clar: "VS1")
    weight_group_09_color_H_VS1 = Diamond.where(weight: 0.9).where(color: "H").where(clar: "VS1")
    weight_group_09_color_I_VS1 = Diamond.where(weight: 0.9).where(color: "I").where(clar: "VS1")
    weight_group_09_color_J_VS1 = Diamond.where(weight: 0.9).where(color: "J").where(clar: "VS1")
    weight_group_09_color_K_VS1 = Diamond.where(weight: 0.9).where(color: "K").where(clar: "VS1")
    weight_group_09_color_L_VS1 = Diamond.where(weight: 0.9).where(color: "L").where(clar: "VS1")
    weight_group_09_color_M_VS1 = Diamond.where(weight: 0.9).where(color: "M").where(clar: "VS1")
    
    weight_group_09_color_D_VS2 = Diamond.where(weight: 0.9).where(color: "D").where(clar: "VS2")
    weight_group_09_color_E_VS2 = Diamond.where(weight: 0.9).where(color: "E").where(clar: "VS2")
    weight_group_09_color_F_VS2 = Diamond.where(weight: 0.9).where(color: "F").where(clar: "VS2")
    weight_group_09_color_G_VS2 = Diamond.where(weight: 0.9).where(color: "G").where(clar: "VS2")
    weight_group_09_color_H_VS2 = Diamond.where(weight: 0.9).where(color: "H").where(clar: "VS2")
    weight_group_09_color_I_VS2 = Diamond.where(weight: 0.9).where(color: "I").where(clar: "VS2")
    weight_group_09_color_J_VS2 = Diamond.where(weight: 0.9).where(color: "J").where(clar: "VS2")
    weight_group_09_color_K_VS2 = Diamond.where(weight: 0.9).where(color: "K").where(clar: "VS2")
    weight_group_09_color_L_VS2 = Diamond.where(weight: 0.9).where(color: "L").where(clar: "VS2")
    weight_group_09_color_M_VS2 = Diamond.where(weight: 0.9).where(color: "M").where(clar: "VS2")
    
    weight_group_09_color_D_SI1 = Diamond.where(weight: 0.9).where(color: "D").where(clar: "SI1")
    weight_group_09_color_E_SI1 = Diamond.where(weight: 0.9).where(color: "E").where(clar: "SI1")
    weight_group_09_color_F_SI1 = Diamond.where(weight: 0.9).where(color: "F").where(clar: "SI1")
    weight_group_09_color_G_SI1 = Diamond.where(weight: 0.9).where(color: "G").where(clar: "SI1")
    weight_group_09_color_H_SI1 = Diamond.where(weight: 0.9).where(color: "H").where(clar: "SI1")
    weight_group_09_color_I_SI1 = Diamond.where(weight: 0.9).where(color: "I").where(clar: "SI1")
    weight_group_09_color_J_SI1 = Diamond.where(weight: 0.9).where(color: "J").where(clar: "SI1")
    weight_group_09_color_K_SI1 = Diamond.where(weight: 0.9).where(color: "K").where(clar: "SI1")
    weight_group_09_color_L_SI1 = Diamond.where(weight: 0.9).where(color: "L").where(clar: "SI1")
    weight_group_09_color_M_SI1 = Diamond.where(weight: 0.9).where(color: "M").where(clar: "SI1")
    
    weight_group_09_color_D_SI2 = Diamond.where(weight: 0.9).where(color: "D").where(clar: "SI2")
    weight_group_09_color_E_SI2 = Diamond.where(weight: 0.9).where(color: "E").where(clar: "SI2")
    weight_group_09_color_F_SI2 = Diamond.where(weight: 0.9).where(color: "F").where(clar: "SI2")
    weight_group_09_color_G_SI2 = Diamond.where(weight: 0.9).where(color: "G").where(clar: "SI2")
    weight_group_09_color_H_SI2 = Diamond.where(weight: 0.9).where(color: "H").where(clar: "SI2")
    weight_group_09_color_I_SI2 = Diamond.where(weight: 0.9).where(color: "I").where(clar: "SI2")
    weight_group_09_color_J_SI2 = Diamond.where(weight: 0.9).where(color: "J").where(clar: "SI2")
    weight_group_09_color_K_SI2 = Diamond.where(weight: 0.9).where(color: "K").where(clar: "SI2")
    weight_group_09_color_L_SI2 = Diamond.where(weight: 0.9).where(color: "L").where(clar: "SI2")
    weight_group_09_color_M_SI2 = Diamond.where(weight: 0.9).where(color: "M").where(clar: "SI2")
 
    #weight1.0-----------------------
    weight_group_10_color_D_IF = Diamond.where(weight: 1).where(color: "D").where(clar: "IF")
    weight_group_10_color_E_IF = Diamond.where(weight: 1).where(color: "E").where(clar: "IF")
    weight_group_10_color_F_IF = Diamond.where(weight: 1).where(color: "F").where(clar: "IF")
    weight_group_10_color_G_IF = Diamond.where(weight: 1).where(color: "G").where(clar: "IF")
    weight_group_10_color_H_IF = Diamond.where(weight: 1).where(color: "H").where(clar: "IF")
    weight_group_10_color_I_IF = Diamond.where(weight: 1).where(color: "I").where(clar: "IF")
    weight_group_10_color_J_IF = Diamond.where(weight: 1).where(color: "J").where(clar: "IF")
    weight_group_10_color_K_IF = Diamond.where(weight: 1).where(color: "K").where(clar: "IF")
    weight_group_10_color_L_IF = Diamond.where(weight: 1).where(color: "L").where(clar: "IF")
    weight_group_10_color_M_IF = Diamond.where(weight: 1).where(color: "M").where(clar: "IF")
    
    weight_group_10_color_D_VVS1 = Diamond.where(weight: 1).where(color: "D").where(clar: "VVS1")
    weight_group_10_color_E_VVS1 = Diamond.where(weight: 1).where(color: "E").where(clar: "VVS1")
    weight_group_10_color_F_VVS1 = Diamond.where(weight: 1).where(color: "F").where(clar: "VVS1")
    weight_group_10_color_G_VVS1 = Diamond.where(weight: 1).where(color: "G").where(clar: "VVS1")
    weight_group_10_color_H_VVS1 = Diamond.where(weight: 1).where(color: "H").where(clar: "VVS1")
    weight_group_10_color_I_VVS1 = Diamond.where(weight: 1).where(color: "I").where(clar: "VVS1")
    weight_group_10_color_J_VVS1 = Diamond.where(weight: 1).where(color: "J").where(clar: "VVS1")
    weight_group_10_color_K_VVS1 = Diamond.where(weight: 1).where(color: "K").where(clar: "VVS1")
    weight_group_10_color_L_VVS1 = Diamond.where(weight: 1).where(color: "L").where(clar: "VVS1")
    weight_group_10_color_M_VVS1 = Diamond.where(weight: 1).where(color: "M").where(clar: "VVS1")
    
    weight_group_10_color_D_VVS2 = Diamond.where(weight: 1).where(color: "D").where(clar: "VVS2")
    weight_group_10_color_E_VVS2 = Diamond.where(weight: 1).where(color: "E").where(clar: "VVS2")
    weight_group_10_color_F_VVS2 = Diamond.where(weight: 1).where(color: "F").where(clar: "VVS2")
    weight_group_10_color_G_VVS2 = Diamond.where(weight: 1).where(color: "G").where(clar: "VVS2")
    weight_group_10_color_H_VVS2 = Diamond.where(weight: 1).where(color: "H").where(clar: "VVS2")
    weight_group_10_color_I_VVS2 = Diamond.where(weight: 1).where(color: "I").where(clar: "VVS2")
    weight_group_10_color_J_VVS2 = Diamond.where(weight: 1).where(color: "J").where(clar: "VVS2")
    weight_group_10_color_K_VVS2 = Diamond.where(weight: 1).where(color: "K").where(clar: "VVS2")
    weight_group_10_color_L_VVS2 = Diamond.where(weight: 1).where(color: "L").where(clar: "VVS2")
    weight_group_10_color_M_VVS2 = Diamond.where(weight: 1).where(color: "M").where(clar: "VVS2")
    
    weight_group_10_color_D_VS1 = Diamond.where(weight: 1).where(color: "D").where(clar: "VS1")
    weight_group_10_color_E_VS1 = Diamond.where(weight: 1).where(color: "E").where(clar: "VS1")
    weight_group_10_color_F_VS1 = Diamond.where(weight: 1).where(color: "F").where(clar: "VS1")
    weight_group_10_color_G_VS1 = Diamond.where(weight: 1).where(color: "G").where(clar: "VS1")
    weight_group_10_color_H_VS1 = Diamond.where(weight: 1).where(color: "H").where(clar: "VS1")
    weight_group_10_color_I_VS1 = Diamond.where(weight: 1).where(color: "I").where(clar: "VS1")
    weight_group_10_color_J_VS1 = Diamond.where(weight: 1).where(color: "J").where(clar: "VS1")
    weight_group_10_color_K_VS1 = Diamond.where(weight: 1).where(color: "K").where(clar: "VS1")
    weight_group_10_color_L_VS1 = Diamond.where(weight: 1).where(color: "L").where(clar: "VS1")
    weight_group_10_color_M_VS1 = Diamond.where(weight: 1).where(color: "M").where(clar: "VS1")
    
    weight_group_10_color_D_VS2 = Diamond.where(weight: 1).where(color: "D").where(clar: "VS2")
    weight_group_10_color_E_VS2 = Diamond.where(weight: 1).where(color: "E").where(clar: "VS2")
    weight_group_10_color_F_VS2 = Diamond.where(weight: 1).where(color: "F").where(clar: "VS2")
    weight_group_10_color_G_VS2 = Diamond.where(weight: 1).where(color: "G").where(clar: "VS2")
    weight_group_10_color_H_VS2 = Diamond.where(weight: 1).where(color: "H").where(clar: "VS2")
    weight_group_10_color_I_VS2 = Diamond.where(weight: 1).where(color: "I").where(clar: "VS2")
    weight_group_10_color_J_VS2 = Diamond.where(weight: 1).where(color: "J").where(clar: "VS2")
    weight_group_10_color_K_VS2 = Diamond.where(weight: 1).where(color: "K").where(clar: "VS2")
    weight_group_10_color_L_VS2 = Diamond.where(weight: 1).where(color: "L").where(clar: "VS2")
    weight_group_10_color_M_VS2 = Diamond.where(weight: 1).where(color: "M").where(clar: "VS2")
    
    weight_group_10_color_D_SI1 = Diamond.where(weight: 1).where(color: "D").where(clar: "SI1")
    weight_group_10_color_E_SI1 = Diamond.where(weight: 1).where(color: "E").where(clar: "SI1")
    weight_group_10_color_F_SI1 = Diamond.where(weight: 1).where(color: "F").where(clar: "SI1")
    weight_group_10_color_G_SI1 = Diamond.where(weight: 1).where(color: "G").where(clar: "SI1")
    weight_group_10_color_H_SI1 = Diamond.where(weight: 1).where(color: "H").where(clar: "SI1")
    weight_group_10_color_I_SI1 = Diamond.where(weight: 1).where(color: "I").where(clar: "SI1")
    weight_group_10_color_J_SI1 = Diamond.where(weight: 1).where(color: "J").where(clar: "SI1")
    weight_group_10_color_K_SI1 = Diamond.where(weight: 1).where(color: "K").where(clar: "SI1")
    weight_group_10_color_L_SI1 = Diamond.where(weight: 1).where(color: "L").where(clar: "SI1")
    weight_group_10_color_M_SI1 = Diamond.where(weight: 1).where(color: "M").where(clar: "SI1")
    
    weight_group_10_color_D_SI2 = Diamond.where(weight: 1).where(color: "D").where(clar: "SI2")
    weight_group_10_color_E_SI2 = Diamond.where(weight: 1).where(color: "E").where(clar: "SI2")
    weight_group_10_color_F_SI2 = Diamond.where(weight: 1).where(color: "F").where(clar: "SI2")
    weight_group_10_color_G_SI2 = Diamond.where(weight: 1).where(color: "G").where(clar: "SI2")
    weight_group_10_color_H_SI2 = Diamond.where(weight: 1).where(color: "H").where(clar: "SI2")
    weight_group_10_color_I_SI2 = Diamond.where(weight: 1).where(color: "I").where(clar: "SI2")
    weight_group_10_color_J_SI2 = Diamond.where(weight: 1).where(color: "J").where(clar: "SI2")
    weight_group_10_color_K_SI2 = Diamond.where(weight: 1).where(color: "K").where(clar: "SI2")
    weight_group_10_color_L_SI2 = Diamond.where(weight: 1).where(color: "L").where(clar: "SI2")
    weight_group_10_color_M_SI2 = Diamond.where(weight: 1).where(color: "M").where(clar: "SI2")

    #weight1.2-----------------------
    weight_group_12_color_D_IF = Diamond.where(weight: 1.2).where(color: "D").where(clar: "IF")
    weight_group_12_color_E_IF = Diamond.where(weight: 1.2).where(color: "E").where(clar: "IF")
    weight_group_12_color_F_IF = Diamond.where(weight: 1.2).where(color: "F").where(clar: "IF")
    weight_group_12_color_G_IF = Diamond.where(weight: 1.2).where(color: "G").where(clar: "IF")
    weight_group_12_color_H_IF = Diamond.where(weight: 1.2).where(color: "H").where(clar: "IF")
    weight_group_12_color_I_IF = Diamond.where(weight: 1.2).where(color: "I").where(clar: "IF")
    weight_group_12_color_J_IF = Diamond.where(weight: 1.2).where(color: "J").where(clar: "IF")
    weight_group_12_color_K_IF = Diamond.where(weight: 1.2).where(color: "K").where(clar: "IF")
    weight_group_12_color_L_IF = Diamond.where(weight: 1.2).where(color: "L").where(clar: "IF")
    weight_group_12_color_M_IF = Diamond.where(weight: 1.2).where(color: "M").where(clar: "IF")
    
    weight_group_12_color_D_VVS1 = Diamond.where(weight: 1.2).where(color: "D").where(clar: "VVS1")
    weight_group_12_color_E_VVS1 = Diamond.where(weight: 1.2).where(color: "E").where(clar: "VVS1")
    weight_group_12_color_F_VVS1 = Diamond.where(weight: 1.2).where(color: "F").where(clar: "VVS1")
    weight_group_12_color_G_VVS1 = Diamond.where(weight: 1.2).where(color: "G").where(clar: "VVS1")
    weight_group_12_color_H_VVS1 = Diamond.where(weight: 1.2).where(color: "H").where(clar: "VVS1")
    weight_group_12_color_I_VVS1 = Diamond.where(weight: 1.2).where(color: "I").where(clar: "VVS1")
    weight_group_12_color_J_VVS1 = Diamond.where(weight: 1.2).where(color: "J").where(clar: "VVS1")
    weight_group_12_color_K_VVS1 = Diamond.where(weight: 1.2).where(color: "K").where(clar: "VVS1")
    weight_group_12_color_L_VVS1 = Diamond.where(weight: 1.2).where(color: "L").where(clar: "VVS1")
    weight_group_12_color_M_VVS1 = Diamond.where(weight: 1.2).where(color: "M").where(clar: "VVS1")
    
    weight_group_12_color_D_VVS2 = Diamond.where(weight: 1.2).where(color: "D").where(clar: "VVS2")
    weight_group_12_color_E_VVS2 = Diamond.where(weight: 1.2).where(color: "E").where(clar: "VVS2")
    weight_group_12_color_F_VVS2 = Diamond.where(weight: 1.2).where(color: "F").where(clar: "VVS2")
    weight_group_12_color_G_VVS2 = Diamond.where(weight: 1.2).where(color: "G").where(clar: "VVS2")
    weight_group_12_color_H_VVS2 = Diamond.where(weight: 1.2).where(color: "H").where(clar: "VVS2")
    weight_group_12_color_I_VVS2 = Diamond.where(weight: 1.2).where(color: "I").where(clar: "VVS2")
    weight_group_12_color_J_VVS2 = Diamond.where(weight: 1.2).where(color: "J").where(clar: "VVS2")
    weight_group_12_color_K_VVS2 = Diamond.where(weight: 1.2).where(color: "K").where(clar: "VVS2")
    weight_group_12_color_L_VVS2 = Diamond.where(weight: 1.2).where(color: "L").where(clar: "VVS2")
    weight_group_12_color_M_VVS2 = Diamond.where(weight: 1.2).where(color: "M").where(clar: "VVS2")
    
    weight_group_12_color_D_VS1 = Diamond.where(weight: 1.2).where(color: "D").where(clar: "VS1")
    weight_group_12_color_E_VS1 = Diamond.where(weight: 1.2).where(color: "E").where(clar: "VS1")
    weight_group_12_color_F_VS1 = Diamond.where(weight: 1.2).where(color: "F").where(clar: "VS1")
    weight_group_12_color_G_VS1 = Diamond.where(weight: 1.2).where(color: "G").where(clar: "VS1")
    weight_group_12_color_H_VS1 = Diamond.where(weight: 1.2).where(color: "H").where(clar: "VS1")
    weight_group_12_color_I_VS1 = Diamond.where(weight: 1.2).where(color: "I").where(clar: "VS1")
    weight_group_12_color_J_VS1 = Diamond.where(weight: 1.2).where(color: "J").where(clar: "VS1")
    weight_group_12_color_K_VS1 = Diamond.where(weight: 1.2).where(color: "K").where(clar: "VS1")
    weight_group_12_color_L_VS1 = Diamond.where(weight: 1.2).where(color: "L").where(clar: "VS1")
    weight_group_12_color_M_VS1 = Diamond.where(weight: 1.2).where(color: "M").where(clar: "VS1")
    
    weight_group_12_color_D_VS2 = Diamond.where(weight: 1.2).where(color: "D").where(clar: "VS2")
    weight_group_12_color_E_VS2 = Diamond.where(weight: 1.2).where(color: "E").where(clar: "VS2")
    weight_group_12_color_F_VS2 = Diamond.where(weight: 1.2).where(color: "F").where(clar: "VS2")
    weight_group_12_color_G_VS2 = Diamond.where(weight: 1.2).where(color: "G").where(clar: "VS2")
    weight_group_12_color_H_VS2 = Diamond.where(weight: 1.2).where(color: "H").where(clar: "VS2")
    weight_group_12_color_I_VS2 = Diamond.where(weight: 1.2).where(color: "I").where(clar: "VS2")
    weight_group_12_color_J_VS2 = Diamond.where(weight: 1.2).where(color: "J").where(clar: "VS2")
    weight_group_12_color_K_VS2 = Diamond.where(weight: 1.2).where(color: "K").where(clar: "VS2")
    weight_group_12_color_L_VS2 = Diamond.where(weight: 1.2).where(color: "L").where(clar: "VS2")
    weight_group_12_color_M_VS2 = Diamond.where(weight: 1.2).where(color: "M").where(clar: "VS2")
    
    weight_group_12_color_D_SI1 = Diamond.where(weight: 1.2).where(color: "D").where(clar: "SI1")
    weight_group_12_color_E_SI1 = Diamond.where(weight: 1.2).where(color: "E").where(clar: "SI1")
    weight_group_12_color_F_SI1 = Diamond.where(weight: 1.2).where(color: "F").where(clar: "SI1")
    weight_group_12_color_G_SI1 = Diamond.where(weight: 1.2).where(color: "G").where(clar: "SI1")
    weight_group_12_color_H_SI1 = Diamond.where(weight: 1.2).where(color: "H").where(clar: "SI1")
    weight_group_12_color_I_SI1 = Diamond.where(weight: 1.2).where(color: "I").where(clar: "SI1")
    weight_group_12_color_J_SI1 = Diamond.where(weight: 1.2).where(color: "J").where(clar: "SI1")
    weight_group_12_color_K_SI1 = Diamond.where(weight: 1.2).where(color: "K").where(clar: "SI1")
    weight_group_12_color_L_SI1 = Diamond.where(weight: 1.2).where(color: "L").where(clar: "SI1")
    weight_group_12_color_M_SI1 = Diamond.where(weight: 1.2).where(color: "M").where(clar: "SI1")
    
    weight_group_12_color_D_SI2 = Diamond.where(weight: 1.2).where(color: "D").where(clar: "SI2")
    weight_group_12_color_E_SI2 = Diamond.where(weight: 1.2).where(color: "E").where(clar: "SI2")
    weight_group_12_color_F_SI2 = Diamond.where(weight: 1.2).where(color: "F").where(clar: "SI2")
    weight_group_12_color_G_SI2 = Diamond.where(weight: 1.2).where(color: "G").where(clar: "SI2")
    weight_group_12_color_H_SI2 = Diamond.where(weight: 1.2).where(color: "H").where(clar: "SI2")
    weight_group_12_color_I_SI2 = Diamond.where(weight: 1.2).where(color: "I").where(clar: "SI2")
    weight_group_12_color_J_SI2 = Diamond.where(weight: 1.2).where(color: "J").where(clar: "SI2")
    weight_group_12_color_K_SI2 = Diamond.where(weight: 1.2).where(color: "K").where(clar: "SI2")
    weight_group_12_color_L_SI2 = Diamond.where(weight: 1.2).where(color: "L").where(clar: "SI2")
    weight_group_12_color_M_SI2 = Diamond.where(weight: 1.2).where(color: "M").where(clar: "SI2")
    
    #weight1.5-----------------------
    weight_group_15_color_D_IF = Diamond.where(weight: 1.5).where(color: "D").where(clar: "IF")
    weight_group_15_color_E_IF = Diamond.where(weight: 1.5).where(color: "E").where(clar: "IF")
    weight_group_15_color_F_IF = Diamond.where(weight: 1.5).where(color: "F").where(clar: "IF")
    weight_group_15_color_G_IF = Diamond.where(weight: 1.5).where(color: "G").where(clar: "IF")
    weight_group_15_color_H_IF = Diamond.where(weight: 1.5).where(color: "H").where(clar: "IF")
    weight_group_15_color_I_IF = Diamond.where(weight: 1.5).where(color: "I").where(clar: "IF")
    weight_group_15_color_J_IF = Diamond.where(weight: 1.5).where(color: "J").where(clar: "IF")
    weight_group_15_color_K_IF = Diamond.where(weight: 1.5).where(color: "K").where(clar: "IF")
    weight_group_15_color_L_IF = Diamond.where(weight: 1.5).where(color: "L").where(clar: "IF")
    weight_group_15_color_M_IF = Diamond.where(weight: 1.5).where(color: "M").where(clar: "IF")
    
    weight_group_15_color_D_VVS1 = Diamond.where(weight: 1.5).where(color: "D").where(clar: "VVS1")
    weight_group_15_color_E_VVS1 = Diamond.where(weight: 1.5).where(color: "E").where(clar: "VVS1")
    weight_group_15_color_F_VVS1 = Diamond.where(weight: 1.5).where(color: "F").where(clar: "VVS1")
    weight_group_15_color_G_VVS1 = Diamond.where(weight: 1.5).where(color: "G").where(clar: "VVS1")
    weight_group_15_color_H_VVS1 = Diamond.where(weight: 1.5).where(color: "H").where(clar: "VVS1")
    weight_group_15_color_I_VVS1 = Diamond.where(weight: 1.5).where(color: "I").where(clar: "VVS1")
    weight_group_15_color_J_VVS1 = Diamond.where(weight: 1.5).where(color: "J").where(clar: "VVS1")
    weight_group_15_color_K_VVS1 = Diamond.where(weight: 1.5).where(color: "K").where(clar: "VVS1")
    weight_group_15_color_L_VVS1 = Diamond.where(weight: 1.5).where(color: "L").where(clar: "VVS1")
    weight_group_15_color_M_VVS1 = Diamond.where(weight: 1.5).where(color: "M").where(clar: "VVS1")
    
    weight_group_15_color_D_VVS2 = Diamond.where(weight: 1.5).where(color: "D").where(clar: "VVS2")
    weight_group_15_color_E_VVS2 = Diamond.where(weight: 1.5).where(color: "E").where(clar: "VVS2")
    weight_group_15_color_F_VVS2 = Diamond.where(weight: 1.5).where(color: "F").where(clar: "VVS2")
    weight_group_15_color_G_VVS2 = Diamond.where(weight: 1.5).where(color: "G").where(clar: "VVS2")
    weight_group_15_color_H_VVS2 = Diamond.where(weight: 1.5).where(color: "H").where(clar: "VVS2")
    weight_group_15_color_I_VVS2 = Diamond.where(weight: 1.5).where(color: "I").where(clar: "VVS2")
    weight_group_15_color_J_VVS2 = Diamond.where(weight: 1.5).where(color: "J").where(clar: "VVS2")
    weight_group_15_color_K_VVS2 = Diamond.where(weight: 1.5).where(color: "K").where(clar: "VVS2")
    weight_group_15_color_L_VVS2 = Diamond.where(weight: 1.5).where(color: "L").where(clar: "VVS2")
    weight_group_15_color_M_VVS2 = Diamond.where(weight: 1.5).where(color: "M").where(clar: "VVS2")
    
    weight_group_15_color_D_VS1 = Diamond.where(weight: 1.5).where(color: "D").where(clar: "VS1")
    weight_group_15_color_E_VS1 = Diamond.where(weight: 1.5).where(color: "E").where(clar: "VS1")
    weight_group_15_color_F_VS1 = Diamond.where(weight: 1.5).where(color: "F").where(clar: "VS1")
    weight_group_15_color_G_VS1 = Diamond.where(weight: 1.5).where(color: "G").where(clar: "VS1")
    weight_group_15_color_H_VS1 = Diamond.where(weight: 1.5).where(color: "H").where(clar: "VS1")
    weight_group_15_color_I_VS1 = Diamond.where(weight: 1.5).where(color: "I").where(clar: "VS1")
    weight_group_15_color_J_VS1 = Diamond.where(weight: 1.5).where(color: "J").where(clar: "VS1")
    weight_group_15_color_K_VS1 = Diamond.where(weight: 1.5).where(color: "K").where(clar: "VS1")
    weight_group_15_color_L_VS1 = Diamond.where(weight: 1.5).where(color: "L").where(clar: "VS1")
    weight_group_15_color_M_VS1 = Diamond.where(weight: 1.5).where(color: "M").where(clar: "VS1")
    
    weight_group_15_color_D_VS2 = Diamond.where(weight: 1.5).where(color: "D").where(clar: "VS2")
    weight_group_15_color_E_VS2 = Diamond.where(weight: 1.5).where(color: "E").where(clar: "VS2")
    weight_group_15_color_F_VS2 = Diamond.where(weight: 1.5).where(color: "F").where(clar: "VS2")
    weight_group_15_color_G_VS2 = Diamond.where(weight: 1.5).where(color: "G").where(clar: "VS2")
    weight_group_15_color_H_VS2 = Diamond.where(weight: 1.5).where(color: "H").where(clar: "VS2")
    weight_group_15_color_I_VS2 = Diamond.where(weight: 1.5).where(color: "I").where(clar: "VS2")
    weight_group_15_color_J_VS2 = Diamond.where(weight: 1.5).where(color: "J").where(clar: "VS2")
    weight_group_15_color_K_VS2 = Diamond.where(weight: 1.5).where(color: "K").where(clar: "VS2")
    weight_group_15_color_L_VS2 = Diamond.where(weight: 1.5).where(color: "L").where(clar: "VS2")
    weight_group_15_color_M_VS2 = Diamond.where(weight: 1.5).where(color: "M").where(clar: "VS2")
    
    weight_group_15_color_D_SI1 = Diamond.where(weight: 1.5).where(color: "D").where(clar: "SI1")
    weight_group_15_color_E_SI1 = Diamond.where(weight: 1.5).where(color: "E").where(clar: "SI1")
    weight_group_15_color_F_SI1 = Diamond.where(weight: 1.5).where(color: "F").where(clar: "SI1")
    weight_group_15_color_G_SI1 = Diamond.where(weight: 1.5).where(color: "G").where(clar: "SI1")
    weight_group_15_color_H_SI1 = Diamond.where(weight: 1.5).where(color: "H").where(clar: "SI1")
    weight_group_15_color_I_SI1 = Diamond.where(weight: 1.5).where(color: "I").where(clar: "SI1")
    weight_group_15_color_J_SI1 = Diamond.where(weight: 1.5).where(color: "J").where(clar: "SI1")
    weight_group_15_color_K_SI1 = Diamond.where(weight: 1.5).where(color: "K").where(clar: "SI1")
    weight_group_15_color_L_SI1 = Diamond.where(weight: 1.5).where(color: "L").where(clar: "SI1")
    weight_group_15_color_M_SI1 = Diamond.where(weight: 1.5).where(color: "M").where(clar: "SI1")
    
    weight_group_15_color_D_SI2 = Diamond.where(weight: 1.5).where(color: "D").where(clar: "SI2")
    weight_group_15_color_E_SI2 = Diamond.where(weight: 1.5).where(color: "E").where(clar: "SI2")
    weight_group_15_color_F_SI2 = Diamond.where(weight: 1.5).where(color: "F").where(clar: "SI2")
    weight_group_15_color_G_SI2 = Diamond.where(weight: 1.5).where(color: "G").where(clar: "SI2")
    weight_group_15_color_H_SI2 = Diamond.where(weight: 1.5).where(color: "H").where(clar: "SI2")
    weight_group_15_color_I_SI2 = Diamond.where(weight: 1.5).where(color: "I").where(clar: "SI2")
    weight_group_15_color_J_SI2 = Diamond.where(weight: 1.5).where(color: "J").where(clar: "SI2")
    weight_group_15_color_K_SI2 = Diamond.where(weight: 1.5).where(color: "K").where(clar: "SI2")
    weight_group_15_color_L_SI2 = Diamond.where(weight: 1.5).where(color: "L").where(clar: "SI2")
    weight_group_15_color_M_SI2 = Diamond.where(weight: 1.5).where(color: "M").where(clar: "SI2")
    
    #0.3_All
    #Date
    weight_group_03_color_D_IF_date = weight_group_03_color_D_IF.pluck(:date)
    #Price_0.3
    weight_group_03_color_D_IF_end_price = weight_group_03_color_D_IF.pluck(:end_price)
    weight_group_03_color_D_VVS1_end_price = weight_group_03_color_D_VVS1.pluck(:end_price)
    weight_group_03_color_D_VVS2_end_price = weight_group_03_color_D_VVS2.pluck(:end_price)
    weight_group_03_color_D_VS1_end_price = weight_group_03_color_D_VS1.pluck(:end_price)
    weight_group_03_color_D_VS2_end_price = weight_group_03_color_D_VS2.pluck(:end_price)
    weight_group_03_color_D_SI1_end_price = weight_group_03_color_D_SI1.pluck(:end_price)
     weight_group_03_color_D_SI2_end_price = weight_group_03_color_D_SI2.pluck(:end_price)

    weight_group_03_color_E_IF_end_price = weight_group_03_color_E_IF.pluck(:end_price)
    weight_group_03_color_E_VVS1_end_price = weight_group_03_color_E_VVS1.pluck(:end_price)
    weight_group_03_color_E_VVS2_end_price = weight_group_03_color_E_VVS2.pluck(:end_price)
    weight_group_03_color_E_VS1_end_price = weight_group_03_color_E_VS1.pluck(:end_price)
    weight_group_03_color_E_VS2_end_price = weight_group_03_color_E_VS2.pluck(:end_price)
    weight_group_03_color_E_SI1_end_price = weight_group_03_color_E_SI1.pluck(:end_price)
    weight_group_03_color_E_SI2_end_price = weight_group_03_color_E_SI2.pluck(:end_price)
    
    weight_group_03_color_F_IF_end_price = weight_group_03_color_F_IF.pluck(:end_price)
    weight_group_03_color_F_VVS1_end_price = weight_group_03_color_F_VVS1.pluck(:end_price)
    weight_group_03_color_F_VVS2_end_price = weight_group_03_color_F_VVS2.pluck(:end_price)
    weight_group_03_color_F_VS1_end_price = weight_group_03_color_F_VS1.pluck(:end_price)
    weight_group_03_color_F_VS2_end_price = weight_group_03_color_F_VS2.pluck(:end_price)
    weight_group_03_color_F_SI1_end_price = weight_group_03_color_F_SI1.pluck(:end_price)
    weight_group_03_color_F_SI2_end_price = weight_group_03_color_F_SI2.pluck(:end_price)
    
    weight_group_03_color_G_IF_end_price = weight_group_03_color_G_IF.pluck(:end_price)
    weight_group_03_color_G_VVS1_end_price = weight_group_03_color_G_VVS1.pluck(:end_price)
    weight_group_03_color_G_VVS2_end_price = weight_group_03_color_G_VVS2.pluck(:end_price)
    weight_group_03_color_G_VS1_end_price = weight_group_03_color_G_VS1.pluck(:end_price)
    weight_group_03_color_G_VS2_end_price = weight_group_03_color_G_VS2.pluck(:end_price)
    weight_group_03_color_G_SI1_end_price = weight_group_03_color_G_SI1.pluck(:end_price)
    weight_group_03_color_G_SI2_end_price = weight_group_03_color_G_SI2.pluck(:end_price)
    
    weight_group_03_color_H_IF_end_price = weight_group_03_color_H_IF.pluck(:end_price)
    weight_group_03_color_H_VVS1_end_price = weight_group_03_color_H_VVS1.pluck(:end_price)
    weight_group_03_color_H_VVS2_end_price = weight_group_03_color_H_VVS2.pluck(:end_price)
    weight_group_03_color_H_VS1_end_price = weight_group_03_color_H_VS1.pluck(:end_price)
    weight_group_03_color_H_VS2_end_price = weight_group_03_color_H_VS2.pluck(:end_price)
    weight_group_03_color_H_SI1_end_price = weight_group_03_color_H_SI1.pluck(:end_price)
    weight_group_03_color_H_SI2_end_price = weight_group_03_color_H_SI2.pluck(:end_price)
    
    weight_group_03_color_I_IF_end_price = weight_group_03_color_I_IF.pluck(:end_price)
    weight_group_03_color_I_VVS1_end_price = weight_group_03_color_I_VVS1.pluck(:end_price)
    weight_group_03_color_I_VVS2_end_price = weight_group_03_color_I_VVS2.pluck(:end_price)
    weight_group_03_color_I_VS1_end_price = weight_group_03_color_I_VS1.pluck(:end_price)
    weight_group_03_color_I_VS2_end_price = weight_group_03_color_I_VS2.pluck(:end_price)
    weight_group_03_color_I_SI1_end_price = weight_group_03_color_I_SI1.pluck(:end_price)
    weight_group_03_color_I_SI2_end_price = weight_group_03_color_I_SI2.pluck(:end_price)
    
    weight_group_03_color_J_IF_end_price = weight_group_03_color_J_IF.pluck(:end_price)
    weight_group_03_color_J_VVS1_end_price = weight_group_03_color_J_VVS1.pluck(:end_price)
    weight_group_03_color_J_VVS2_end_price = weight_group_03_color_J_VVS2.pluck(:end_price)
    weight_group_03_color_J_VS1_end_price = weight_group_03_color_J_VS1.pluck(:end_price)
    weight_group_03_color_J_VS2_end_price = weight_group_03_color_J_VS2.pluck(:end_price)
    weight_group_03_color_J_SI1_end_price = weight_group_03_color_J_SI1.pluck(:end_price)
    weight_group_03_color_J_SI2_end_price = weight_group_03_color_J_SI2.pluck(:end_price)
    
    weight_group_03_color_K_IF_end_price = weight_group_03_color_K_IF.pluck(:end_price)
    weight_group_03_color_K_VVS1_end_price = weight_group_03_color_K_VVS1.pluck(:end_price)
    weight_group_03_color_K_VVS2_end_price = weight_group_03_color_K_VVS2.pluck(:end_price)
    weight_group_03_color_K_VS1_end_price = weight_group_03_color_K_VS1.pluck(:end_price)
    weight_group_03_color_K_VS2_end_price = weight_group_03_color_K_VS2.pluck(:end_price)
    weight_group_03_color_K_SI1_end_price = weight_group_03_color_K_SI1.pluck(:end_price)
    weight_group_03_color_K_SI2_end_price = weight_group_03_color_K_SI2.pluck(:end_price)
    
    weight_group_03_color_L_IF_end_price = weight_group_03_color_L_IF.pluck(:end_price)
    weight_group_03_color_L_VVS1_end_price = weight_group_03_color_L_VVS1.pluck(:end_price)
    weight_group_03_color_L_VVS2_end_price = weight_group_03_color_L_VVS2.pluck(:end_price)
    weight_group_03_color_L_VS1_end_price = weight_group_03_color_L_VS1.pluck(:end_price)
    weight_group_03_color_L_VS2_end_price = weight_group_03_color_L_VS2.pluck(:end_price)
    weight_group_03_color_L_SI1_end_price = weight_group_03_color_L_SI1.pluck(:end_price)
    weight_group_03_color_L_SI2_end_price = weight_group_03_color_L_SI2.pluck(:end_price)
    
    weight_group_03_color_M_IF_end_price = weight_group_03_color_M_IF.pluck(:end_price)
    weight_group_03_color_M_VVS1_end_price = weight_group_03_color_M_VVS1.pluck(:end_price)
    weight_group_03_color_M_VVS2_end_price = weight_group_03_color_M_VVS2.pluck(:end_price)
    weight_group_03_color_M_VS1_end_price = weight_group_03_color_M_VS1.pluck(:end_price)
    weight_group_03_color_M_VS2_end_price = weight_group_03_color_M_VS2.pluck(:end_price)
    weight_group_03_color_M_SI1_end_price = weight_group_03_color_M_SI1.pluck(:end_price)
    weight_group_03_color_M_SI2_end_price = weight_group_03_color_M_SI2.pluck(:end_price)
    
    
    
    @chart = LazyHighCharts::HighChart.new('graph') do |f|
      # binding.pry
      f.title(:text => "Diamond Price Chart")
      # f.xAxis(type: 'datetime')
      f.xAxis(:categories => weight_group_03_color_D_IF_date)
      f.series(:name => "0.3_D_IF", :data => weight_group_03_color_D_IF_end_price)
      f.series(:name => "0.3_D_VVS1", :data => weight_group_03_color_D_VVS1_end_price)
      f.series(:name => "0.3_D_VVS2", :data => weight_group_03_color_D_VVS2_end_price)
      f.series(:name => "0.3_D_VS1", :data => weight_group_03_color_D_VS1_end_price)
      f.series(:name => "0.3_D_VS2", :data => weight_group_03_color_D_VS2_end_price)
      f.series(:name => "0.3_D_SI1", :data => weight_group_03_color_D_SI1_end_price)
      f.series(:name => "0.3_D_SI2", :data => weight_group_03_color_D_SI2_end_price)
      
      
      f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
      # f.chart({:defaultSeriesType=>"column"})
    end
    
  end
  
  def create
    @diamond = Diamond.new(diamond_params)
    @diamond.save
    redirect_to root_path , notice: 'データを保存しました'
  end
  
  private
  def diamond_params
    params.require(:diamond).permit(:date, :weight, :clar, :start_price, :end_price, :low_price, :high_price )
  end
  
end
